version: '3'
services:
        static-website:
                build: ajaxApplication
                container_name: static-website
                ports:
                        - 8080:80
                links:
                        - user-service
                depends_on:
                        - user-service
        user-service:
                build: restfulServer
                container_name: user-service
                volumes:
                        - ./restfulServer/log:/opt/app/log
                        - ./restfulServer/configFiles:/opt/app/config
                ports:
                        - 8080:8080
                links:
                        - mongodb
                depends_on:
                        - mongodb
        mongodb:
                image: mongo:latest
                container_name: "mongodb"
                ports:
                        - 27017:27017
                command: mongod --auth
