version: '3'
services:
        static-website:
                build: ajaxApplication
                restart: always
                container_name: static-website
                ports:
                        - 9001:80
                depends_on:
                        - user-service
        user-service:
                build: restfulServer
                restart: always
                container_name: user-service
                env_file:
                        - variables.env
                volumes:
                        - ./restfulServer/log:/opt/app/log
                        - ./restfulServer/configFiles:/opt/app/config
                ports:
                        - 9002:80
                links:
                        - mongodb
                depends_on:
                        - config-mongo
        mongodb:
                image: mongo:3.4.2
                container_name: "mongodb"
                ports:
                        - 27017:27017
                command: mongod --auth
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=admin
                        - MONGO_INITDB_ROOT_PASSWORD=defaultPassword
        config-mongo:
                build: configMongoDB
                container_name: "config-mongo"
                links:
                        - mongodb
                depends_on:
                        - mongodb
        proxy:
                build: reverseProxy
                restart: always
                container_name: reverseProxy
                volumes:
                        - ./reverseProxy/log:/var/log/nginx
                ports:
                        - 8080:80
                depends_on:
                        - static-website
                        - user-service
