build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /go/src/application/application
    production:
      name: application:latest
      dockerfile: Dockerfile.production
      depends_on:
        - builder
